version: "3.0"
services:
  file-fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-fe
    ports:
      - "8083:8083"
    volumes:
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - /etc/localtime:/etc/localtime
    networks:
      - file-network
    restart: always
networks:
  file-network:
    external: true